### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nerdbeere** [eLtMosen/FreakXoHBingo#4]
Hi,

wir hatten heute eine kleine Refactoring Session mit dem Code aus diesem Repository.
Wir machen das einmal die Woche mit unterschiedlichem Code um einfach besser in Code Reviews zu werden. Falls dich interessiert was meine Kollegen so von sich gegeben haben, kannst du gerne mal in die Commits reinschauen: https://github.com/nerdbeere/FreakXoHBingo/commits/refactoring

Gruesse aus Unterfoehring :)

![img_0421](https://cloud.githubusercontent.com/assets/423218/11718470/64a84f3a-9f56-11e5-8170-5c85834997fa.JPG)

**Comment by moWerk** [comment]
Besten Gruß zurück aus Düsseldorf!

Danke für das kostenlose Tutorial am lebenden Exempel :D
Falls Ihr Euch fragt wie der creative Code-Stil zustande kommt: 6 Jahre Basic, 10 Jahre Pascal, 14 Jahre pause, 6 Wochen JS.

Nochmal Danke an alle!

**Comment by moWerk** [comment]
Und nochmal Hi Julian!

Kannst Du aus euren Commits noch ein Pull-Request zusammenfassen oder mir sonst kurz erläutern wie ich die in die Master Branch joine? 
Besten Gruß! Timo

**Comment by moWerk** [comment]
Hi again Julian!
Hab eure refectoring hilfe händisch integriert! 
Danke nochmal für die Hinweise :D
